cliente: Cliente.o Paquetedatagrama.o Socketdatagrama.o Solicitud.o
	g++ Socketdatagrama.o Solicitud.o Paquetedatagrama.o Cliente.o -o Cliente
cliente.o: Cliente.cpp
	g++ -Wall -c Cliente.cpp
Paquetedatagrama.o: Paquetedatagrama.cpp
	g++ -Wall -c Paquetedatagrama.cpp
Socketdatagrama.o:Socketdatagrama.cpp 
	g++ -Wall -c Socketdatagrama.cpp
Solicitud.o: Solicitud.cpp
	gcc -Wall -c Solicitud.cpp
